image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Env
    command: |
      # setup .env file:
      echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> .env
      echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}" >> .env
      echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> .env
      echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> .env
      echo "AWS_MODEL=claude-3-haiku-20240307" >> .env
      echo "GOOGLE_MODEL=gemini-1.0-pro" >> .env
      echo "OPENAI_MODEL=gpt-4" >> .env
      echo 'DEFUALT_PROVIDER="Open AI"' >> .env
      echo 'DEFUALT_MODEL="gpt-4-turbo-preview" >> .env
      echo "ENCRYPTION_KEY=neoconversesecretkey" >> .env
      echo "NEXT_PUBLIC_BACKEND_HOST=${NEXT_PUBLIC_BACKEND_HOST}" >> .env
      echo "NEXT_PUBLIC_BACKEND_UNAME=${NEXT_PUBLIC_BACKEND_UNAME}" >> .env
      echo "NEXT_PUBLIC_BACKEND_PWD=${NEXT_PUBLIC_BACKEND_PWD}" >> .env
      echo "NEXT_PUBLIC_BACKEND_DATABASE=${NEXT_PUBLIC_BACKEND_DATABASE}" >> .env
      echo "ENV=DEV" >> .env

  - name: Start neoconverse
    command: |

      # Install requirements
      npm install --legacy-peer-deps

      # Build        
      sudo npm run build

      # Start neoconverse
      npm run start
      
ports:
  - port: 8000
    onOpen: notify
    visibility: public

  - port: 5173
    onOpen: open-browser
    visibility: public

